name: Close inactive PRs
on:
  # schedule:
    # 北京时间 0,6,12,18 点
    # - cron: "0 2,8,14,20 * * *"
  workflow_dispatch:
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: "joe mama"
          close-pr-message: "joe mama"
          days-before-pr-stale: 7
          days-before-pr-close: 1
          any-of-pr-labels: "joe mama"
          stale-pr-label: "joe mama"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
