name: Weekly stargating

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/CFPAOrg/Minecraft-Mod-Language-Package.git
          git fetch upstream

      - name: Create/update sync branch
        run: |
          git checkout main
          git pull origin main
          BRANCH="sync-upstream"
          git branch -D $BRANCH || true
          git checkout -b $BRANCH
          git merge upstream/main || true
          git push origin $BRANCH --force

      - name: Create/update PR
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Weekly stargating $(date +%Y/%m/%d)"
          body: "This PR stargates CFPAOrg/Minecraft-Mod-Language-Package:main."
          branch: sync-upstream
          base: main
          delete-branch: false

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
