name: Weekly stargating

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/CFPAOrg/Minecraft-Mod-Language-Package.git
          git fetch upstream

      - name: Create/update sync branch
        run: |
          git checkout main
          git pull origin main
          BRANCH="upstream-stargating"
          git branch -D $BRANCH || true
          git checkout -b $BRANCH
          git merge upstream/main || true
          git push origin $BRANCH --force

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync upstream"
          title: "Weekly stargating $(date +%Y/%m/%d)"
          body: "This PR stargates CFPAOrg/Minecraft-Mod-Language-Package:main."
          branch: upstream-stargating
          base: main
          delete-branch: true

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
